### ISSUE TITLE
Uncaught Error: Directory should be a string

### ISSUE THREAD

**Issue by ternstor** [ayurmedia/atom-sync-cygwin#7]
1. Configure `.sync-config.cson` with the following:

```
remote:
  host: "internal-host"
  user: "ternstor"
  path: "repos/demo"
behaviour:
  uploadOnSave: true
  syncDownOnOpen: true
  forgetConsole: false
  autoHideConsole: true
  alwaysSyncAll: false
option:
  deleteFiles: false
  exclude: [
    ".sync-config.cson"
    "node_modules"
    "tmp"
    "vendor"
  ]
```

2. Right click on `demo` project folder.
3. Click on "Sync" -> "Sync Remote -> Local".

**Atom**: 1.20.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-sync-cygwin](https://github.com/ayurmedia/atom-sync-cygwin) package 0.9.16

### Stack Trace

Uncaught Error: Directory should be a string

```
At /Users/ternstor/.atom/packages/atom-sync-cygwin/node_modules/rsync/rsync.js:415

Error: Directory should be a string
    at Rsync.cwd (/packages/atom-sync-cygwin/node_modules/rsync/rsync.js:415:19)
    at module.exports (/packages/atom-sync-cygwin/lib/service/rsync-service.coffee:45:9)
    at Object.sync (/packages/atom-sync-cygwin/lib/controller/service-controller.coffee:98:5)
    at Object.onSync (/packages/atom-sync-cygwin/lib/controller/service-controller.coffee:77:6)
    at /packages/atom-sync-cygwin/lib/atom-sync-cygwin.coffee:27:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -7:18.6.0 atom-sync-cygwin:download-directory (div.header.list-item.project-root-header)
     -6:51.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -5:35.1.0 atom-sync-cygwin:configure (div.header.list-item.project-root-header)
     -5:19.1.0 core:paste (input.hidden-input)
     -5:18.4.0 core:backspace (input.hidden-input)
     -5:18.2.0 core:save (input.hidden-input)
     -4:36 atom-sync-cygwin:download-directory (div.header.list-item.project-root-header)
     -4:33.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  5x -2:15.2.0 atom-sync-cygwin:download-directory (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-sync-cygwin 0.9.16 
MagicPython 1.0.12 
Sublime-Style-Column-Selection 1.7.4 
```
